### PR TITLE
Fix index definition parse logic to handle nulls sort order

### LINKED ISSUE #13: Support NULLS FIRST and NULLS LAST on index creation
Low priority.

### PR DESCRIPTION
**Pull request by mysticmind**
- Add implementation to handle nulls sort order
- Add unit tests
- Add XML doc comments

Fixes #13

### CODE REVIEW

**Comment by mysticmind** [comment]
Fixes https://github.com/JasperFx/weasel/issues/13

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs [hunk 1]
```diff
@@ -436,20 +452,47 @@ private static string canonicizeColumn(string expression)
...
             {
                 order = SortOrder.Desc;
+                nullsSort = null;
                 return expression.Substring(0, expression.Length - 6) + ")";
             }
+            else if (expression.EndsWith("DESC NULLS FIRST)"))
+            {
+                order = SortOrder.Desc;
+                nullsSort = Tables.NullsSortOrder.First;
+                return expression.Substring(0, expression.Length - 18) + ")";
```
Comment (oskardudycz) [inline src/Weasel.Postgresql/Tables/IndexDefinition.cs:467]: **SUGGESTION:** I know that it was already like that, but it might be worth making `"DESC NULLS FIRST)"` a const, and using here its length instead of "magic" number (same for other places). It's not a blocker for me if you don't agree.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs [hunk 2]
```diff
@@ -436,20 +452,47 @@ private static string canonicizeColumn(string expression)
             return CanonicizeCast(expression);
         }
 
-        private static string removeSortOrderFromExpression(string expression, out SortOrder order)
+        private static string removeSortOrderFromExpression(string expression, out SortOrder order, out NullsSortOrder? nullsSort)
```
Comment (oskardudycz) [inline src/Weasel.Postgresql/Tables/IndexDefinition.cs:455]: **SUGGESTION:** Maybe we could return tuple here instead of multiple `out` params? As it's a private method then I think it would be more explicit and won't mess with public API.

File: src/Weasel.Postgresql/Tables/NullsSortOrder.cs [hunk 3]
```diff
@@ -0,0 +1,13 @@
+namespace Weasel.Postgresql.Tables
+{
+    /// <summary>
+    /// Specifies the null sort order
+    /// </summary>
+    public enum NullsSortOrder
+    {
```
Comment (oskardudycz) [inline src/Weasel.Postgresql/Tables/NullsSortOrder.cs:7]: **SUGGESTION:** We could add `None`, or `NotDefined` option and use it in the code, then it'd be more explicit than null.

**Review by oskardudycz — APPROVED** [review]
@mysticmind, I added a few minor suggestions. They're non-blockers. Good job 👍

**Comment by mysticmind** [comment]
> @mysticmind, I added a few minor suggestions. They're non-blockers. Good job 👍

Thanks Oskar, will attempt to address the suggestions.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs (hunk 1 above)
Comment (jeremydmiller) [reply src/Weasel.Postgresql/Tables/IndexDefinition.cs:467]: Not really an issue if it's only used once. Kinda helpful to see the DB terminology in place here.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs [hunk 4]
```diff
@@ -63,6 +63,8 @@ protected virtual string deriveIndexName()
 
         public SortOrder SortOrder { get; set; } = SortOrder.Asc;
 
+        public NullsSortOrder? NullsSortOrder { get; set; } = null;
```
Comment (jeremydmiller) [inline src/Weasel.Postgresql/Tables/IndexDefinition.cs:66]: This was on me here, but we could use some Xml comments. I'm happy to help w/ that after this PR.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs [hunk 5]
```diff
@@ -436,20 +452,47 @@ private static string canonicizeColumn(string expression)
             return CanonicizeCast(expression);
         }
 
-        private static string removeSortOrderFromExpression(string expression, out SortOrder order)
+        private static string removeSortOrderFromExpression(string expression, out SortOrder order, out NullsSortOrder? nullsSort)
         {
```
Comment (jeremydmiller) [inline src/Weasel.Postgresql/Tables/IndexDefinition.cs:456]: Would the new C# pattern matching stuff help here maybe? Not a big thing.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs (hunk 1 above)
Comment (mysticmind) [reply src/Weasel.Postgresql/Tables/IndexDefinition.cs]: Fixed and handled this suggestion.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs (hunk 2 above)
Comment (mysticmind) [reply src/Weasel.Postgresql/Tables/IndexDefinition.cs]: Fixed and handled this suggestion.

File: src/Weasel.Postgresql/Tables/NullsSortOrder.cs (hunk 3 above)
Comment (mysticmind) [reply src/Weasel.Postgresql/Tables/NullsSortOrder.cs:7]: Added `None`. Fixed and handled this suggestion.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs (hunk 4 above)
Comment (mysticmind) [reply src/Weasel.Postgresql/Tables/IndexDefinition.cs]: Xml comments added.

File: src/Weasel.Postgresql/Tables/IndexDefinition.cs (hunk 5 above)
Comment (mysticmind) [reply src/Weasel.Postgresql/Tables/IndexDefinition.cs:495]: yeah, this nicely fit in the pattern matching. Fixed and addressed it.

**Comment by mysticmind** [comment]
I went ahead and merged this PR.
